development:
  clients:
    default:
      uri: mongodb+srv://P2dppOAbUfXjf5HM:P2dppOAbUfXjf5HM@cluster0.vdwiq.mongodb.net/bloging_platform_development?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
test:
  clients:
    default:
      database: bloging_platform_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
